services:
  main:
    container_name: friends_poll_bot
    platform: linux/amd64
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 5001:5001
    command: npm run start
    depends_on:
      - mongodb
    restart: always
  mongodb:
    image: mongo:5.0.2
    # command: [--auth]
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongodb:/data/db
volumes:
  mongodb:
